services:
  - name: development-proxy
    type: web
    plan: starter
    region: frankfurt
    runtime: ruby
    buildCommand: render/build.sh
    startCommand: render/start.sh
    autoDeploy: false
